In [2]:
import pandas as pd

In [3]:
path = 'F:\Big_Data\Military\Arms exports\Arms exports.csv'
df = pd.read_csv(path)
df

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,ABW,Arms exports (SIPRI trend indicator values),MS.MIL.XPRT.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,AFG,Arms exports (SIPRI trend indicator values),MS.MIL.XPRT.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,AGO,Arms exports (SIPRI trend indicator values),MS.MIL.XPRT.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Albania,ALB,Arms exports (SIPRI trend indicator values),MS.MIL.XPRT.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andorra,AND,Arms exports (SIPRI trend indicator values),MS.MIL.XPRT.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,XKX,Arms exports (SIPRI trend indicator values),MS.MIL.XPRT.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,"Yemen, Rep.",YEM,Arms exports (SIPRI trend indicator values),MS.MIL.XPRT.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,South Africa,ZAF,Arms exports (SIPRI trend indicator values),MS.MIL.XPRT.KD,27000000.0,33000000.0,NaN,NaN,NaN,NaN,...,71000000.0,184000000.0,103000000.0,65000000.0,58000000.0,74000000.0,77000000.0,65000000.0,145000000.0,NaN
262,Zambia,ZMB,Arms exports (SIPRI trend indicator values),MS.MIL.XPRT.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,Zimbabwe,ZWE,Arms exports (SIPRI trend indicator values),MS.MIL.XPRT.KD,NaN,NaN,NaN,NaN,3000000.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_drop = df.drop(['Country Code', 'Indicator Name', 'Indicator Code'], axis=1)
df_drop

,Country Name,1960,1961,1962,1963,1964,1965,1966,1967,1968,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Aruba,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afghanistan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Angola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Albania,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Andorra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,Kosovo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,"Yemen, Rep.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,South Africa,27000000.0,33000000.0,NaN,NaN,NaN,NaN,NaN,4000000.0,NaN,...,71000000.0,184000000.0,103000000.0,65000000.0,58000000.0,74000000.0,77000000.0,65000000.0,145000000.0,NaN
262,Zambia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
263,Zimbabwe,NaN,NaN,NaN,NaN,3000000.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df_drop.set_index('Country Name', inplace=True)
df_transposed = df_drop.T
df_transposed

Country Name,Aruba,Afghanistan,Angola,Albania,Andorra,Arab World,United Arab Emirates,Argentina,Armenia,American Samoa,...,Virgin Islands (U.S.),Vietnam,Vanuatu,World,Samoa,Kosovo,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
1960,NaN,NaN,NaN,NaN,NaN,3000000.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27000000.0,NaN,NaN
1961,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,33000000.0,NaN,NaN
1962,NaN,NaN,NaN,NaN,NaN,9000000.0,NaN,6000000.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1963,NaN,NaN,NaN,NaN,NaN,8000000.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1964,NaN,NaN,NaN,NaN,NaN,2000000.0,NaN,4000000.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016,NaN,NaN,NaN,NaN,NaN,NaN,92000000.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74000000.0,NaN,NaN
2017,NaN,NaN,NaN,NaN,NaN,NaN,97000000.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77000000.0,NaN,NaN
2018,NaN,NaN,NaN,NaN,NaN,NaN,113000000.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65000000.0,NaN,NaN
2019,NaN,NaN,NaN,NaN,NaN,NaN,104000000.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,145000000.0,NaN,NaN
2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
import numpy as np
df_transposed[np.isnan(df_transposed)] = 0
df_transposed

Country Name,Aruba,Afghanistan,Angola,Albania,Andorra,Arab World,United Arab Emirates,Argentina,Armenia,American Samoa,...,Virgin Islands (U.S.),Vietnam,Vanuatu,World,Samoa,Kosovo,"Yemen, Rep.",South Africa,Zambia,Zimbabwe
1960,0.0,0.0,0.0,0.0,0.0,3000000.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27000000.0,0.0,0.0
1961,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33000000.0,0.0,0.0
1962,0.0,0.0,0.0,0.0,0.0,9000000.0,0.0,6000000.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1963,0.0,0.0,0.0,0.0,0.0,8000000.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1964,0.0,0.0,0.0,0.0,0.0,2000000.0,0.0,4000000.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3000000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016,0.0,0.0,0.0,0.0,0.0,0.0,92000000.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74000000.0,0.0,0.0
2017,0.0,0.0,0.0,0.0,0.0,0.0,97000000.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,77000000.0,0.0,0.0
2018,0.0,0.0,0.0,0.0,0.0,0.0,113000000.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,65000000.0,0.0,0.0
2019,0.0,0.0,0.0,0.0,0.0,0.0,104000000.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,145000000.0,0.0,0.0
2020,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
df_transposed.to_csv('F:\Big_Data\Military\Arms exports\df_transposed.csv')

In [7]:
path2 = 'F:\Big_Data\Military\Arms exports\df_transposed2.csv'
afp = pd.read_csv(path2)
afp

,Time,United Arab Emirates,Argentina,Australia,Austria,Azerbaijan,Burundi,Belgium,Benin,Brazil,...,Uzbekistan,"Venezuela, RB",Vietnam,Vanuatu,Samoa,Kosovo,Yemen,South Africa,Zambia,Zimbabwe
0,1960,0,0,0,0,0,0,3000000,0,2000000,...,0,0,0,0,0,0,0,27000000,0,0
1,1961,0,0,2000000,0,0,0,0,0,12000000,...,0,0,0,0,0,0,0,33000000,0,0
2,1962,0,6000000,4000000,0,0,0,2000000,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1963,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1964,0,4000000,0,0,0,0,1000000,0,0,...,0,0,0,0,0,0,0,0,0,3000000
5,1965,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,1966,0,0,0,1000000,0,0,12000000,0,0,...,0,0,0,0,0,0,0,0,0,0
7,1967,0,0,0,1000000,0,0,0,0,0,...,0,0,0,0,0,0,0,4000000,0,0
8,1968,0,8000000,0,1000000,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,1969,0,0,26000000,1000000,0,0,5000000,0,3000000,...,0,17000000,0,0,0,0,0,14000000,0,0
10,1970,0,0,17000000,1000000,0,0,0,0,0,...,0,0,0,0,0,0,0,3000000,0,0
11,1971,0,0,36000000,1000000,0,0,0,0,0,...,0,0,0,0,0,0,0,5000000,0,0
12,1972,0,11000000,6000000,1000000,0,0,0,0,0,...,0,0,0,0,0,0,0,12000000,0,0
13,1973,0,0,72000000,1000000,0,0,0,0,0,...,0,0,0,0,0,0,0,1000000,0,0
14,1974,8000000,0,92000000,0,0,0,0,0,32000000,...,0,0,0,0,0,0,0,2000000,0,0
15,1975,0,0,131000000,0,0,0,0,0,59000000,...,0,13000000,0,0,0,0,6000000,18000000,0,0
16,1976,0,1000000,113000000,0,0,0,0,0,104000000,...,0,0,0,0,0,0,0,16000000,0,0
17,1977,0,0,62000000,0,0,0,0,0,145000000,...,0,0,0,0,0,0,0,0,0,0
18,1978,0,0,21000000,37000000,0,0,2000000,0,179000000,...,0,0,0,0,0,0,0,0,0,0
19,1979,0,8000000,22000000,126000000,0,0,3000000,0,70000000,...,0,0,0,0,0,0,0,0,0,0
20,1980,0,1000000,15000000,54000000,0,0,1000000,0,156000000,...,0,0,0,0,0,0,0,39000000,0,0
21,1981,0,24000000,15000000,70000000,0,0,19000000,0,62000000,...,0,0,0,0,0,0,0,39000000,0,0
22,1982,0,3000000,24000000,60000000,0,0,41000000,0,122000000,...,0,0,0,0,0,0,0,1000000,0,0
23,1983,14000000,1000000,31000000,56000000,0,0,89000000,0,196000000,...,0,0,0,0,0,0,0,0,0,0
24,1984,0,0,62000000,58000000,0,0,115000000,0,267000000,...,0,0,0,0,0,0,0,0,0,0
25,1985,0,0,10000000,248000000,0,0,3000000,0,197000000,...,0,0,0,0,0,0,0,25000000,0,0
26,1986,22000000,0,57000000,40000000,0,0,19000000,0,126000000,...,0,0,0,0,0,0,51000000,25000000,0,0
27,1987,1000000,4000000,89000000,30000000,0,0,0,0,191000000,...,0,0,11000000,0,0,0,0,28000000,0,0
28,1988,0,1000000,18000000,12000000,0,0,18000000,0,183000000,...,0,0,0,0,0,0,0,25000000,0,0
29,1989,0,0,18000000,12000000,0,0,36000000,0,47000000,...,0,0,0,0,0,0,0,0,0,0
30,1990,2000000,6000000,158000000,30000000,0,0,1000000,0,96000000,...,0,0,0,0,0,0,0,0,2000000,0
31,1991,0,0,85000000,20000000,0,0,1000000,0,114000000,...,0,0,0,0,0,0,0,54000000,0,0
32,1992,0,0,0,20000000,0,0,0,0,90000000,...,0,0,0,0,0,0,0,75000000,0,0
33,1993,0,11000000,30000000,10000000,0,0,0,0,36000000,...,0,0,0,0,0,0,0,54000000,0,0
34,1994,0,4000000,36000000,17000000,0,0,33000000,0,54000000,...,0,0,0,0,0,0,0,11000000,0,0
35,1995,28000000,5000000,36000000,0,0,0,167000000,0,33000000,...,0,0,0,0,0,0,0,17000000,0,0
36,1996,6000000,0,16000000,18000000,0,0,59000000,0,23000000,...,0,0,0,0,0,0,0,31000000,0,0
37,1997,32000000,0,20000000,1000000,0,0,93000000,0,23000000,...,0,0,0,0,0,0,0,7000000,0,0
38,1998,0,0,4000000,29000000,0,0,46000000,0,16000000,...,0,0,0,0,0,0,0,22000000,0,0
39,1999,0,0,0,23000000,0,0,45000000,0,0,...,0,0,0,0,0,0,0,28000000,0,0
40,2000,0,2000000,0,24000000,0,0,26000000,0,0,...,0,0,0,0,0,0,0,21000000,0,0
41,2001,0,6000000,43000000,17000000,0,0,37000000,0,0,...,0,0,0,0,0,0,0,37000000,0,4000000
42,2002,0,2000000,47000000,83000000,0,0,35000000,0,19000000,...,0,0,0,0,0,0,0,17000000,0,0
43,2003,0,0,44000000,3000000,0,0,15000000,0,0,...,252000000,0,0,0,0,0,0,43000000,0,0
44,2004,3000000,0,2000000,3000000,0,0,47000000,0,46000000,...,126000000,1000000,0,0,0,0,0,72000000,0,0
45,2005,11000000,0,49000000,4000000,0,0,159000000,0,1000000,...,4000000,0,0,0,0,0,0,30000000,0,0
46,2006,17000000,2000000,14000000,63000000,0,0,59000000,0,44000000,...,0,7000000,14000000,0,0,0,0,187000000,0,0
47,2007,3000000,0,18000000,100000000,0,0,19000000,0,53000000,...,0,0,0,0,0,0,0,127000000,0,0
48,2008,0,0,26000000,15000000,0,0,217000000,0,92000000,...,0,3000000,0,0,0,0,0,141000000,0,0
49,2009,34000000,0,80000000,44000000,0,0,243000000,0,43000000,...,209000000,40000000,0,0,0,0,0,103000000,0,0
50,2010,39000000,0,115000000,49000000,0,0,9000000,0,143000000,...,209000000,0,0,0,0,0,0,235000000,0,0
51,2011,3000000,1000000,143000000,53000000,0,0,116000000,0,31000000,...,209000000,0,0,0,0,0,0,71000000,0,0
52,2012,69000000,0,45000000,25000000,0,0,22000000,0,33000000,...,0,0,0,0,0,0,0,184000000,0,0
53,2013,106000000,0,54000000,29000000,0,0,55000000,0,31000000,...,0,0,0,0,0,0,0,103000000,0,0
54,2014,73000000,0,97000000,15000000,0,0,10000000,0,42000000,...,0,0,0,0,0,0,0,65000000,0,0
55,2015,131000000,0,87000000,10000000,0,0,12000000,0,41000000,...,34000000,0,0,0,0,0,0,58000000,0,0
56,2016,92000000,0,134000000,16000000,0,0,7000000,0,111000000,...,68000000,0,0,0,0,0,0,74000000,0,0
57,2017,97000000,0,98000000,22000000,0,0,12000000,0,37000000,...,0,0,0,0,0,0,0,77000000,0,0
58,2018,113000000,0,38000000,6000000,0,0,16000000,0,100000000,...,0,0,0,0,0,0,0,65000000,0,0
59,2019,104000000,0,148000000,3000000,0,0,42000000,0,10000000,...,0,0,0,0,0,0,0,145000000,0,0

In [8]:
afp_indexed = afp.set_index('Time')
afp_indexed

,United Arab Emirates,Argentina,Australia,Austria,Azerbaijan,Burundi,Belgium,Benin,Brazil,Canada,...,Uzbekistan,"Venezuela, RB",Vietnam,Vanuatu,Samoa,Kosovo,Yemen,South Africa,Zambia,Zimbabwe
Time,,,,,,,,,,,,,,,,,,,,,
1960,0,0,0,0,0,0,3000000,0,2000000,52000000,...,0,0,0,0,0,0,0,27000000,0,0
1961,0,0,2000000,0,0,0,0,0,12000000,314000000,...,0,0,0,0,0,0,0,33000000,0,0
1962,0,6000000,4000000,0,0,0,2000000,0,0,188000000,...,0,0,0,0,0,0,0,0,0,0
1963,0,0,0,0,0,0,0,0,0,214000000,...,0,0,0,0,0,0,0,0,0,0
1964,0,4000000,0,0,0,0,1000000,0,0,253000000,...,0,0,0,0,0,0,0,0,0,3000000
1965,0,0,0,0,0,0,0,0,0,111000000,...,0,0,0,0,0,0,0,0,0,0
1966,0,0,0,1000000,0,0,12000000,0,0,102000000,...,0,0,0,0,0,0,0,0,0,0
1967,0,0,0,1000000,0,0,0,0,0,53000000,...,0,0,0,0,0,0,0,4000000,0,0
1968,0,8000000,0,1000000,0,0,0,0,0,197000000,...,0,0,0,0,0,0,0,0,0,0
1969,0,0,26000000,1000000,0,0,5000000,0,3000000,166000000,...,0,17000000,0,0,0,0,0,14000000,0,0
1970,0,0,17000000,1000000,0,0,0,0,0,196000000,...,0,0,0,0,0,0,0,3000000,0,0
1971,0,0,36000000,1000000,0,0,0,0,0,293000000,...,0,0,0,0,0,0,0,5000000,0,0
1972,0,11000000,6000000,1000000,0,0,0,0,0,327000000,...,0,0,0,0,0,0,0,12000000,0,0
1973,0,0,72000000,1000000,0,0,0,0,0,130000000,...,0,0,0,0,0,0,0,1000000,0,0
1974,8000000,0,92000000,0,0,0,0,0,32000000,121000000,...,0,0,0,0,0,0,0,2000000,0,0
1975,0,0,131000000,0,0,0,0,0,59000000,148000000,...,0,13000000,0,0,0,0,6000000,18000000,0,0
1976,0,1000000,113000000,0,0,0,0,0,104000000,329000000,...,0,0,0,0,0,0,0,16000000,0,0
1977,0,0,62000000,0,0,0,0,0,145000000,169000000,...,0,0,0,0,0,0,0,0,0,0
1978,0,0,21000000,37000000,0,0,2000000,0,179000000,190000000,...,0,0,0,0,0,0,0,0,0,0
1979,0,8000000,22000000,126000000,0,0,3000000,0,70000000,195000000,...,0,0,0,0,0,0,0,0,0,0
1980,0,1000000,15000000,54000000,0,0,1000000,0,156000000,161000000,...,0,0,0,0,0,0,0,39000000,0,0
1981,0,24000000,15000000,70000000,0,0,19000000,0,62000000,130000000,...,0,0,0,0,0,0,0,39000000,0,0
1982,0,3000000,24000000,60000000,0,0,41000000,0,122000000,259000000,...,0,0,0,0,0,0,0,1000000,0,0
1983,14000000,1000000,31000000,56000000,0,0,89000000,0,196000000,120000000,...,0,0,0,0,0,0,0,0,0,0
1984,0,0,62000000,58000000,0,0,115000000,0,267000000,108000000,...,0,0,0,0,0,0,0,0,0,0
1985,0,0,10000000,248000000,0,0,3000000,0,197000000,100000000,...,0,0,0,0,0,0,0,25000000,0,0
1986,22000000,0,57000000,40000000,0,0,19000000,0,126000000,261000000,...,0,0,0,0,0,0,51000000,25000000,0,0
1987,1000000,4000000,89000000,30000000,0,0,0,0,191000000,279000000,...,0,0,11000000,0,0,0,0,28000000,0,0
1988,0,1000000,18000000,12000000,0,0,18000000,0,183000000,153000000,...,0,0,0,0,0,0,0,25000000,0,0
1989,0,0,18000000,12000000,0,0,36000000,0,47000000,49000000,...,0,0,0,0,0,0,0,0,0,0
1990,2000000,6000000,158000000,30000000,0,0,1000000,0,96000000,101000000,...,0,0,0,0,0,0,0,0,2000000,0
1991,0,0,85000000,20000000,0,0,1000000,0,114000000,121000000,...,0,0,0,0,0,0,0,54000000,0,0
1992,0,0,0,20000000,0,0,0,0,90000000,143000000,...,0,0,0,0,0,0,0,75000000,0,0
1993,0,11000000,30000000,10000000,0,0,0,0,36000000,146000000,...,0,0,0,0,0,0,0,54000000,0,0
1994,0,4000000,36000000,17000000,0,0,33000000,0,54000000,167000000,...,0,0,0,0,0,0,0,11000000,0,0
1995,28000000,5000000,36000000,0,0,0,167000000,0,33000000,263000000,...,0,0,0,0,0,0,0,17000000,0,0
1996,6000000,0,16000000,18000000,0,0,59000000,0,23000000,160000000,...,0,0,0,0,0,0,0,31000000,0,0
1997,32000000,0,20000000,1000000,0,0,93000000,0,23000000,95000000,...,0,0,0,0,0,0,0,7000000,0,0
1998,0,0,4000000,29000000,0,0,46000000,0,16000000,40000000,...,0,0,0,0,0,0,0,22000000,0,0
1999,0,0,0,23000000,0,0,45000000,0,0,79000000,...,0,0,0,0,0,0,0,28000000,0,0
2000,0,2000000,0,24000000,0,0,26000000,0,0,74000000,...,0,0,0,0,0,0,0,21000000,0,0
2001,0,6000000,43000000,17000000,0,0,37000000,0,0,129000000,...,0,0,0,0,0,0,0,37000000,0,4000000
2002,0,2000000,47000000,83000000,0,0,35000000,0,19000000,183000000,...,0,0,0,0,0,0,0,17000000,0,0
2003,0,0,44000000,3000000,0,0,15000000,0,0,288000000,...,252000000,0,0,0,0,0,0,43000000,0,0
2004,3000000,0,2000000,3000000,0,0,47000000,0,46000000,286000000,...,126000000,1000000,0,0,0,0,0,72000000,0,0
2005,11000000,0,49000000,4000000,0,0,159000000,0,1000000,242000000,...,4000000,0,0,0,0,0,0,30000000,0,0
2006,17000000,2000000,14000000,63000000,0,0,59000000,0,44000000,244000000,...,0,7000000,14000000,0,0,0,0,187000000,0,0
2007,3000000,0,18000000,100000000,0,0,19000000,0,53000000,342000000,...,0,0,0,0,0,0,0,127000000,0,0
2008,0,0,26000000,15000000,0,0,217000000,0,92000000,247000000,...,0,3000000,0,0,0,0,0,141000000,0,0
2009,34000000,0,80000000,44000000,0,0,243000000,0,43000000,192000000,...,209000000,40000000,0,0,0,0,0,103000000,0,0
2010,39000000,0,115000000,49000000,0,0,9000000,0,143000000,250000000,...,209000000,0,0,0,0,0,0,235000000,0,0
2011,3000000,1000000,143000000,53000000,0,0,116000000,0,31000000,330000000,...,209000000,0,0,0,0,0,0,71000000,0,0
2012,69000000,0,45000000,25000000,0,0,22000000,0,33000000,277000000,...,0,0,0,0,0,0,0,184000000,0,0
2013,106000000,0,54000000,29000000,0,0,55000000,0,31000000,191000000,...,0,0,0,0,0,0,0,103000000,0,0
2014,73000000,0,97000000,15000000,0,0,10000000,0,42000000,203000000,...,0,0,0,0,0,0,0,65000000,0,0
2015,131000000,0,87000000,10000000,0,0,12000000,0,41000000,346000000,...,34000000,0,0,0,0,0,0,58000000,0,0
2016,92000000,0,134000000,16000000,0,0,7000000,0,111000000,120000000,...,68000000,0,0,0,0,0,0,74000000,0,0
2017,97000000,0,98000000,22000000,0,0,12000000,0,37000000,72000000,...,0,0,0,0,0,0,0,77000000,0,0
2018,113000000,0,38000000,6000000,0,0,16000000,0,100000000,111000000,...,0,0,0,0,0,0,0,65000000,0,0
2019,104000000,0,148000000,3000000,0,0,42000000,0,10000000,188000000,...,0,0,0,0,0,0,0,145000000,0,0

In [9]:
afp_indexed.isnull().sum().sum()

0

In [10]:
afp_indexed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 60 entries, 1960 to 2019
Columns: 132 entries, United Arab Emirates to Zimbabwe
dtypes: int64(132)
memory usage: 62.3 KB

In [11]:
afp_indexed.describe()

,United Arab Emirates,Argentina,Australia,Austria,Azerbaijan,Burundi,Belgium,Benin,Brazil,Canada,...,Uzbekistan,"Venezuela, RB",Vietnam,Vanuatu,Samoa,Kosovo,Yemen,South Africa,Zambia,Zimbabwe
count,6.000000e+01,6.000000e+01,6.000000e+01,6.000000e+01,60.0,60.0,6.000000e+01,60.0,6.000000e+01,6.000000e+01,...,6.000000e+01,6.000000e+01,6.000000e+01,60.0,60.0,60.0,6.000000e+01,6.000000e+01,6.000000e+01,6.000000e+01
mean,1.680000e+07,1.850000e+06,4.350000e+07,2.605000e+07,0.0,0.0,3.286667e+07,0.0,5.858333e+07,1.833000e+08,...,1.851667e+07,1.350000e+06,4.166667e+05,0.0,0.0,0.0,9.500000e+05,4.118333e+07,3.333333e+04,1.166667e+05
std,3.412778e+07,4.007726e+06,4.390417e+07,3.996457e+07,0.0,0.0,5.308786e+07,0.0,6.539509e+07,8.314951e+07,...,5.758516e+07,5.833349e+06,2.279545e+06,0.0,0.0,0.0,6.616428e+06,5.231440e+07,2.581989e+05,6.402242e+05
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.000000e+00,0.0,0.000000e+00,4.000000e+07,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,0.000000e+00,0.000000e+00,9.000000e+06,1.000000e+06,0.0,0.0,0.000000e+00,0.0,7.500000e+05,1.200000e+08,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000e+00,1.750000e+06,0.000000e+00,0.000000e+00
50%,0.000000e+00,0.000000e+00,2.800000e+07,1.500000e+07,0.0,0.0,1.200000e+07,0.0,3.650000e+07,1.760000e+08,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000e+00,2.500000e+07,0.000000e+00,0.000000e+00
75%,1.175000e+07,2.000000e+06,6.450000e+07,3.175000e+07,0.0,0.0,4.125000e+07,0.0,9.700000e+07,2.507500e+08,...,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000e+00,5.975000e+07,0.000000e+00,0.000000e+00
max,1.310000e+08,2.400000e+07,1.580000e+08,2.480000e+08,0.0,0.0,2.430000e+08,0.0,2.670000e+08,3.460000e+08,...,2.520000e+08,4.000000e+07,1.400000e+07,0.0,0.0,0.0,5.100000e+07,2.350000e+08,2.000000e+06,4.000000e+06

In [12]:
pip install bar_chart_race

Requirement already satisfied: bar_chart_race in c:\users\cgsun\anaconda3\lib\site-packages (0.1.0)
Requirement already satisfied: pandas>=0.24 in c:\users\cgsun\anaconda3\lib\site-packages (from bar_chart_race) (1.0.1)
Requirement already satisfied: matplotlib>=3.1 in c:\users\cgsun\anaconda3\lib\site-packages (from bar_chart_race) (3.1.3)
Requirement already satisfied: pytz>=2017.2 in c:\users\cgsun\anaconda3\lib\site-packages (from pandas>=0.24->bar_chart_race) (2019.3)
Requirement already satisfied: numpy>=1.13.3 in c:\users\cgsun\anaconda3\lib\site-packages (from pandas>=0.24->bar_chart_race) (1.18.1)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\cgsun\anaconda3\lib\site-packages (from pandas>=0.24->bar_chart_race) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\cgsun\anaconda3\lib\site-packages (from matplotlib>=3.1->bar_chart_race) (1.1.0)
Requirement already satisfied: cycler>=0.10 in c:\users\cgsun\anaconda3\lib\site-packages (from matplotlib>=3.1->bar_chart_race) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\cgsun\anaconda3\lib\site-packages (from matplotlib>=3.1->bar_chart_race) (2.4.6)
Requirement already satisfied: six>=1.5 in c:\users\cgsun\anaconda3\lib\site-packages (from python-dateutil>=2.6.1->pandas>=0.24->bar_chart_race) (1.14.0)
Requirement already satisfied: setuptools in c:\users\cgsun\anaconda3\lib\site-packages (from kiwisolver>=1.0.1->matplotlib>=3.1->bar_chart_race) (45.2.0.post20200210)
Note: you may need to restart the kernel to use updated packages.

In [13]:
import bar_chart_race as bcr
bcr.bar_chart_race(afp_indexed, 'F:\Big_Data\Military\Arms exports\exports.mp4', n_bars=10, steps_per_period=1000, period_length=1000,
                  title='Top10 Arms Exporter',  figsize=(5, 3))

C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 127 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 128 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 129 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 130 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 131 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 132 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 133 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 134 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 135 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 136 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 137 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 138 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 139 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 140 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 141 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 142 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 143 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 144 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 145 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 146 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 147 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 148 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 149 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 150 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 151 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 152 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 153 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 154 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 155 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 156 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 157 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 158 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:211: RuntimeWarning: Glyph 159 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:180: RuntimeWarning: Glyph 127 missing from current font.
  font.set_text(s, 0, flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 128 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 129 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 130 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 131 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 132 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 133 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 134 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 135 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 136 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 137 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 138 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 139 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 140 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 141 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 142 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 143 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 144 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 145 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 146 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 147 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 148 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 149 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 150 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 151 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 152 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 153 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 154 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 155 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 156 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 157 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 158 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:176: RuntimeWarning: Glyph 159 missing from current font.
  font.load_char(ord(s), flags=flags)
C:\Users\cgsun\anaconda3\lib\site-packages\bar_chart_race\_make_chart.py:226: UserWarning: Some of your columns never make an appearance in the animation. To reduce color repetition, set `filter_column_colors` to `True`
  warnings.warn("Some of your columns never make an appearance in the animation. "